### ISSUE TITLE
'tree' symbols rendered incorrectly in PDF documents

### ISSUE THREAD

**Issue by ghost** [build2/style#1]
Line symbols generated by `tree` command are rendered incorrectly in every PDF document

![pdf-symbols](https://user-images.githubusercontent.com/32795850/56714427-6ebc2200-673d-11e9-8c8c-67822b9ecc8e.png)

**Comment by boris-kolpackov** [comment]
Yes, a known issue. See this mailing list thread for some discussion: https://lists.build2.org/archives/users/2019-March/000599.html

**Comment by boris-kolpackov** [comment]
We've "fixed" this for the next release with a stop-gap solution of using ASCII-only characters. Hopefully we will come up with a better solution eventually.
